### ISSUE TITLE
Allow passing of data attributes to select options

### ISSUE THREAD

**Issue by alanvardy** [code-and-effect/ex_effective_bootstrap#1]
This is probably a non-trivial feature to implement.

Currently the Phoenix select_tag does not seem to have an option to pass in data- attributes to the individual select options. (I.e. providing a site_id for filtering).

https://elixirforum.com/t/add-classes-to-the-select-options-using-phoenix-html-form-select/1704

The solution could involve using jQuery to add the data attributes on to the select.

**Comment by alanvardy** [comment]
And without fail, after opening an issue I find the solution!

```
select: [
[key: "something", value: 1, data_site: 5],
[key: "another ...", value: 2, data_site: 5],
[key: "third thing", value: 3, data_site: 6]
]
```

Thank you!

**Comment by danajanssen** [comment]
:D
